main: me.oska.UniversalGUI
name: UniversalGUI
version: 3.0.8
author: Oska
api-version: 1.16
description: Customize User Interface via Configuration and Extensible Modules.
softdepend: [ Citizens, PlaceholderAPI ]
commands:
  ugui:
    description: UniversalGUI default command.
    usage: /ugui